// Font loader utility with static import mapping for Vite compatibility
import figlet from 'figlet'

// All available figlet fonts (295 total)
export const fontImports: Record<string, () => Promise<{ default: string }>> = {
  '1Row': () => import('figlet/importable-fonts/1Row.js'),
  '3-D': () => import('figlet/importable-fonts/3-D.js'),
  '3D Diagonal': () => import('figlet/importable-fonts/3D Diagonal.js'),
  '3D-ASCII': () => import('figlet/importable-fonts/3D-ASCII.js'),
  '3x5': () => import('figlet/importable-fonts/3x5.js'),
  '4Max': () => import('figlet/importable-fonts/4Max.js'),
  '5 Line Oblique': () => import('figlet/importable-fonts/5 Line Oblique.js'),
  'Acrobatic': () => import('figlet/importable-fonts/Acrobatic.js'),
  'Alligator': () => import('figlet/importable-fonts/Alligator.js'),
  'Alligator2': () => import('figlet/importable-fonts/Alligator2.js'),
  'Alpha': () => import('figlet/importable-fonts/Alpha.js'),
  'Alphabet': () => import('figlet/importable-fonts/Alphabet.js'),
  'AMC 3 Line': () => import('figlet/importable-fonts/AMC 3 Line.js'),
  'AMC 3 Liv1': () => import('figlet/importable-fonts/AMC 3 Liv1.js'),
  'AMC AAA01': () => import('figlet/importable-fonts/AMC AAA01.js'),
  'AMC Neko': () => import('figlet/importable-fonts/AMC Neko.js'),
  'AMC Razor': () => import('figlet/importable-fonts/AMC Razor.js'),
  'AMC Razor2': () => import('figlet/importable-fonts/AMC Razor2.js'),
  'AMC Slash': () => import('figlet/importable-fonts/AMC Slash.js'),
  'AMC Slider': () => import('figlet/importable-fonts/AMC Slider.js'),
  'AMC Thin': () => import('figlet/importable-fonts/AMC Thin.js'),
  'AMC Tubes': () => import('figlet/importable-fonts/AMC Tubes.js'),
  'AMC Untitled': () => import('figlet/importable-fonts/AMC Untitled.js'),
  'ANSI Regular': () => import('figlet/importable-fonts/ANSI Regular.js'),
  'ANSI Shadow': () => import('figlet/importable-fonts/ANSI Shadow.js'),
  'Arrows': () => import('figlet/importable-fonts/Arrows.js'),
  'ASCII New Roman': () => import('figlet/importable-fonts/ASCII New Roman.js'),
  'Avatar': () => import('figlet/importable-fonts/Avatar.js'),
  'B1FF': () => import('figlet/importable-fonts/B1FF.js'),
  'Banner': () => import('figlet/importable-fonts/Banner.js'),
  'Banner3-D': () => import('figlet/importable-fonts/Banner3-D.js'),
  'Banner3': () => import('figlet/importable-fonts/Banner3.js'),
  'Banner4': () => import('figlet/importable-fonts/Banner4.js'),
  'Barbwire': () => import('figlet/importable-fonts/Barbwire.js'),
  'Basic': () => import('figlet/importable-fonts/Basic.js'),
  'Bear': () => import('figlet/importable-fonts/Bear.js'),
  'Bell': () => import('figlet/importable-fonts/Bell.js'),
  'Benjamin': () => import('figlet/importable-fonts/Benjamin.js'),
  'Big Chief': () => import('figlet/importable-fonts/Big Chief.js'),
  'Big Money-ne': () => import('figlet/importable-fonts/Big Money-ne.js'),
  'Big Money-nw': () => import('figlet/importable-fonts/Big Money-nw.js'),
  'Big Money-se': () => import('figlet/importable-fonts/Big Money-se.js'),
  'Big Money-sw': () => import('figlet/importable-fonts/Big Money-sw.js'),
  'Big': () => import('figlet/importable-fonts/Big.js'),
  'Bigfig': () => import('figlet/importable-fonts/Bigfig.js'),
  'Binary': () => import('figlet/importable-fonts/Binary.js'),
  'Block': () => import('figlet/importable-fonts/Block.js'),
  'Blocks': () => import('figlet/importable-fonts/Blocks.js'),
  'Bloody': () => import('figlet/importable-fonts/Bloody.js'),
  'BlurVision ASCII': () => import('figlet/importable-fonts/BlurVision ASCII.js'),
  'Bolger': () => import('figlet/importable-fonts/Bolger.js'),
  'Braced': () => import('figlet/importable-fonts/Braced.js'),
  'Bright': () => import('figlet/importable-fonts/Bright.js'),
  'Broadway KB': () => import('figlet/importable-fonts/Broadway KB.js'),
  'Broadway': () => import('figlet/importable-fonts/Broadway.js'),
  'Bubble': () => import('figlet/importable-fonts/Bubble.js'),
  'Bulbhead': () => import('figlet/importable-fonts/Bulbhead.js'),
  'Caligraphy': () => import('figlet/importable-fonts/Caligraphy.js'),
  'Caligraphy2': () => import('figlet/importable-fonts/Caligraphy2.js'),
  'Calvin S': () => import('figlet/importable-fonts/Calvin S.js'),
  'Cards': () => import('figlet/importable-fonts/Cards.js'),
  'Catwalk': () => import('figlet/importable-fonts/Catwalk.js'),
  'Chiseled': () => import('figlet/importable-fonts/Chiseled.js'),
  'Chunky': () => import('figlet/importable-fonts/Chunky.js'),
  'Coinstak': () => import('figlet/importable-fonts/Coinstak.js'),
  'Cola': () => import('figlet/importable-fonts/Cola.js'),
  'Colossal': () => import('figlet/importable-fonts/Colossal.js'),
  'Computer': () => import('figlet/importable-fonts/Computer.js'),
  'Contessa': () => import('figlet/importable-fonts/Contessa.js'),
  'Contrast': () => import('figlet/importable-fonts/Contrast.js'),
  'Cosmike': () => import('figlet/importable-fonts/Cosmike.js'),
  'Cosmike2': () => import('figlet/importable-fonts/Cosmike2.js'),
  'Crawford': () => import('figlet/importable-fonts/Crawford.js'),
  'Crawford2': () => import('figlet/importable-fonts/Crawford2.js'),
  'Crazy': () => import('figlet/importable-fonts/Crazy.js'),
  'Cricket': () => import('figlet/importable-fonts/Cricket.js'),
  'Cursive': () => import('figlet/importable-fonts/Cursive.js'),
  'Cyberlarge': () => import('figlet/importable-fonts/Cyberlarge.js'),
  'Cybermedium': () => import('figlet/importable-fonts/Cybermedium.js'),
  'Cybersmall': () => import('figlet/importable-fonts/Cybersmall.js'),
  'Cygnet': () => import('figlet/importable-fonts/Cygnet.js'),
  'DANC4': () => import('figlet/importable-fonts/DANC4.js'),
  'Dancing Font': () => import('figlet/importable-fonts/Dancing Font.js'),
  'Decimal': () => import('figlet/importable-fonts/Decimal.js'),
  'Def Leppard': () => import('figlet/importable-fonts/Def Leppard.js'),
  'Delta Corps Priest 1': () => import('figlet/importable-fonts/Delta Corps Priest 1.js'),
  'DiamFont': () => import('figlet/importable-fonts/DiamFont.js'),
  'Diamond': () => import('figlet/importable-fonts/Diamond.js'),
  'Diet Cola': () => import('figlet/importable-fonts/Diet Cola.js'),
  'Digital': () => import('figlet/importable-fonts/Digital.js'),
  'Doh': () => import('figlet/importable-fonts/Doh.js'),
  'Doom': () => import('figlet/importable-fonts/Doom.js'),
  'DOS Rebel': () => import('figlet/importable-fonts/DOS Rebel.js'),
  'Dot Matrix': () => import('figlet/importable-fonts/Dot Matrix.js'),
  'Double Shorts': () => import('figlet/importable-fonts/Double Shorts.js'),
  'Double': () => import('figlet/importable-fonts/Double.js'),
  'Dr Pepper': () => import('figlet/importable-fonts/Dr Pepper.js'),
  'DWhistled': () => import('figlet/importable-fonts/DWhistled.js'),
  'Efti Chess': () => import('figlet/importable-fonts/Efti Chess.js'),
  'Efti Font': () => import('figlet/importable-fonts/Efti Font.js'),
  'Efti Italic': () => import('figlet/importable-fonts/Efti Italic.js'),
  'Efti Piti': () => import('figlet/importable-fonts/Efti Piti.js'),
  'Efti Robot': () => import('figlet/importable-fonts/Efti Robot.js'),
  'Efti Wall': () => import('figlet/importable-fonts/Efti Wall.js'),
  'Efti Water': () => import('figlet/importable-fonts/Efti Water.js'),
  'Electronic': () => import('figlet/importable-fonts/Electronic.js'),
  'Elite': () => import('figlet/importable-fonts/Elite.js'),
  'Epic': () => import('figlet/importable-fonts/Epic.js'),
  'Fender': () => import('figlet/importable-fonts/Fender.js'),
  'Filter': () => import('figlet/importable-fonts/Filter.js'),
  'Fire Font-k': () => import('figlet/importable-fonts/Fire Font-k.js'),
  'Fire Font-s': () => import('figlet/importable-fonts/Fire Font-s.js'),
  'Flipped': () => import('figlet/importable-fonts/Flipped.js'),
  'Flower Power': () => import('figlet/importable-fonts/Flower Power.js'),
  'Four Tops': () => import('figlet/importable-fonts/Four Tops.js'),
  'Fraktur': () => import('figlet/importable-fonts/Fraktur.js'),
  'Fun Face': () => import('figlet/importable-fonts/Fun Face.js'),
  'Fun Faces': () => import('figlet/importable-fonts/Fun Faces.js'),
  'Fuzzy': () => import('figlet/importable-fonts/Fuzzy.js'),
  'Georgi16': () => import('figlet/importable-fonts/Georgi16.js'),
  'Georgia11': () => import('figlet/importable-fonts/Georgia11.js'),
  'Ghost': () => import('figlet/importable-fonts/Ghost.js'),
  'Ghoulish': () => import('figlet/importable-fonts/Ghoulish.js'),
  'Glenyn': () => import('figlet/importable-fonts/Glenyn.js'),
  'Goofy': () => import('figlet/importable-fonts/Goofy.js'),
  'Gothic': () => import('figlet/importable-fonts/Gothic.js'),
  'Graceful': () => import('figlet/importable-fonts/Graceful.js'),
  'Gradient': () => import('figlet/importable-fonts/Gradient.js'),
  'Graffiti': () => import('figlet/importable-fonts/Graffiti.js'),
  'Greek': () => import('figlet/importable-fonts/Greek.js'),
  'Heart Left': () => import('figlet/importable-fonts/Heart Left.js'),
  'Heart Right': () => import('figlet/importable-fonts/Heart Right.js'),
  'Henry 3D': () => import('figlet/importable-fonts/Henry 3D.js'),
  'Hex': () => import('figlet/importable-fonts/Hex.js'),
  'Hieroglyphs': () => import('figlet/importable-fonts/Hieroglyphs.js'),
  'Hollywood': () => import('figlet/importable-fonts/Hollywood.js'),
  'Horizontal Left': () => import('figlet/importable-fonts/Horizontal Left.js'),
  'Horizontal Right': () => import('figlet/importable-fonts/Horizontal Right.js'),
  'ICL-1900': () => import('figlet/importable-fonts/ICL-1900.js'),
  'Impossible': () => import('figlet/importable-fonts/Impossible.js'),
  'Invita': () => import('figlet/importable-fonts/Invita.js'),
  'Isometric1': () => import('figlet/importable-fonts/Isometric1.js'),
  'Isometric2': () => import('figlet/importable-fonts/Isometric2.js'),
  'Isometric3': () => import('figlet/importable-fonts/Isometric3.js'),
  'Isometric4': () => import('figlet/importable-fonts/Isometric4.js'),
  'Italic': () => import('figlet/importable-fonts/Italic.js'),
  'Ivrit': () => import('figlet/importable-fonts/Ivrit.js'),
  'Jacky': () => import('figlet/importable-fonts/Jacky.js'),
  'Jazmine': () => import('figlet/importable-fonts/Jazmine.js'),
  'Jerusalem': () => import('figlet/importable-fonts/Jerusalem.js'),
  'JS Block Letters': () => import('figlet/importable-fonts/JS Block Letters.js'),
  'JS Bracket Letters': () => import('figlet/importable-fonts/JS Bracket Letters.js'),
  'JS Capital Curves': () => import('figlet/importable-fonts/JS Capital Curves.js'),
  'JS Cursive': () => import('figlet/importable-fonts/JS Cursive.js'),
  'JS Stick Letters': () => import('figlet/importable-fonts/JS Stick Letters.js'),
  'Katakana': () => import('figlet/importable-fonts/Katakana.js'),
  'Kban': () => import('figlet/importable-fonts/Kban.js'),
  'Keyboard': () => import('figlet/importable-fonts/Keyboard.js'),
  'Knob': () => import('figlet/importable-fonts/Knob.js'),
  'Konto Slant': () => import('figlet/importable-fonts/Konto Slant.js'),
  'Konto': () => import('figlet/importable-fonts/Konto.js'),
  'Larry 3D 2': () => import('figlet/importable-fonts/Larry 3D 2.js'),
  'Larry 3D': () => import('figlet/importable-fonts/Larry 3D.js'),
  'LCD': () => import('figlet/importable-fonts/LCD.js'),
  'Lean': () => import('figlet/importable-fonts/Lean.js'),
  'Letters': () => import('figlet/importable-fonts/Letters.js'),
  'Lil Devil': () => import('figlet/importable-fonts/Lil Devil.js'),
  'Line Blocks': () => import('figlet/importable-fonts/Line Blocks.js'),
  'Linux': () => import('figlet/importable-fonts/Linux.js'),
  'Lockergnome': () => import('figlet/importable-fonts/Lockergnome.js'),
  'Madrid': () => import('figlet/importable-fonts/Madrid.js'),
  'Marquee': () => import('figlet/importable-fonts/Marquee.js'),
  'Maxfour': () => import('figlet/importable-fonts/Maxfour.js'),
  'Merlin1': () => import('figlet/importable-fonts/Merlin1.js'),
  'Merlin2': () => import('figlet/importable-fonts/Merlin2.js'),
  'Mike': () => import('figlet/importable-fonts/Mike.js'),
  'Mini': () => import('figlet/importable-fonts/Mini.js'),
  'miniwi': () => import('figlet/importable-fonts/miniwi.js'),
  'Mirror': () => import('figlet/importable-fonts/Mirror.js'),
  'Mnemonic': () => import('figlet/importable-fonts/Mnemonic.js'),
  'Modular': () => import('figlet/importable-fonts/Modular.js'),
  'Morse': () => import('figlet/importable-fonts/Morse.js'),
  'Morse2': () => import('figlet/importable-fonts/Morse2.js'),
  'Moscow': () => import('figlet/importable-fonts/Moscow.js'),
  'Mshebrew210': () => import('figlet/importable-fonts/Mshebrew210.js'),
  'Muzzle': () => import('figlet/importable-fonts/Muzzle.js'),
  'Nancyj-Fancy': () => import('figlet/importable-fonts/Nancyj-Fancy.js'),
  'Nancyj-Improved': () => import('figlet/importable-fonts/Nancyj-Improved.js'),
  'Nancyj-Underlined': () => import('figlet/importable-fonts/Nancyj-Underlined.js'),
  'Nancyj': () => import('figlet/importable-fonts/Nancyj.js'),
  'Nipples': () => import('figlet/importable-fonts/Nipples.js'),
  'NScript': () => import('figlet/importable-fonts/NScript.js'),
  'NT Greek': () => import('figlet/importable-fonts/NT Greek.js'),
  'NV Script': () => import('figlet/importable-fonts/NV Script.js'),
  'O8': () => import('figlet/importable-fonts/O8.js'),
  'Octal': () => import('figlet/importable-fonts/Octal.js'),
  'Ogre': () => import('figlet/importable-fonts/Ogre.js'),
  'Old Banner': () => import('figlet/importable-fonts/Old Banner.js'),
  'OS2': () => import('figlet/importable-fonts/OS2.js'),
  'Pagga': () => import('figlet/importable-fonts/Pagga.js'),
  'Patorjk-HeX': () => import('figlet/importable-fonts/Patorjk-HeX.js'),
  'Patorjk\'s Cheese': () => import('figlet/importable-fonts/Patorjk\'s Cheese.js'),
  'Pawp': () => import('figlet/importable-fonts/Pawp.js'),
  'Peaks Slant': () => import('figlet/importable-fonts/Peaks Slant.js'),
  'Peaks': () => import('figlet/importable-fonts/Peaks.js'),
  'Pebbles': () => import('figlet/importable-fonts/Pebbles.js'),
  'Pepper': () => import('figlet/importable-fonts/Pepper.js'),
  'Poison': () => import('figlet/importable-fonts/Poison.js'),
  'Puffy': () => import('figlet/importable-fonts/Puffy.js'),
  'Puzzle': () => import('figlet/importable-fonts/Puzzle.js'),
  'Pyramid': () => import('figlet/importable-fonts/Pyramid.js'),
  'Rammstein': () => import('figlet/importable-fonts/Rammstein.js'),
  'Rectangles': () => import('figlet/importable-fonts/Rectangles.js'),
  'Red Phoenix': () => import('figlet/importable-fonts/Red Phoenix.js'),
  'Relief': () => import('figlet/importable-fonts/Relief.js'),
  'Relief2': () => import('figlet/importable-fonts/Relief2.js'),
  'Reverse': () => import('figlet/importable-fonts/Reverse.js'),
  'Roman': () => import('figlet/importable-fonts/Roman.js'),
  'Rot13': () => import('figlet/importable-fonts/Rot13.js'),
  'Rotated': () => import('figlet/importable-fonts/Rotated.js'),
  'Rounded': () => import('figlet/importable-fonts/Rounded.js'),
  'Rowan Cap': () => import('figlet/importable-fonts/Rowan Cap.js'),
  'Rozzo': () => import('figlet/importable-fonts/Rozzo.js'),
  'RubiFont': () => import('figlet/importable-fonts/RubiFont.js'),
  'Runic': () => import('figlet/importable-fonts/Runic.js'),
  'Runyc': () => import('figlet/importable-fonts/Runyc.js'),
  'S Blood': () => import('figlet/importable-fonts/S Blood.js'),
  'Santa Clara': () => import('figlet/importable-fonts/Santa Clara.js'),
  'Script': () => import('figlet/importable-fonts/Script.js'),
  'Serifcap': () => import('figlet/importable-fonts/Serifcap.js'),
  'Shaded Blocky': () => import('figlet/importable-fonts/Shaded Blocky.js'),
  'Shadow': () => import('figlet/importable-fonts/Shadow.js'),
  'Shimrod': () => import('figlet/importable-fonts/Shimrod.js'),
  'Short': () => import('figlet/importable-fonts/Short.js'),
  'SL Script': () => import('figlet/importable-fonts/SL Script.js'),
  'Slant Relief': () => import('figlet/importable-fonts/Slant Relief.js'),
  'Slant': () => import('figlet/importable-fonts/Slant.js'),
  'Slide': () => import('figlet/importable-fonts/Slide.js'),
  'Small Caps': () => import('figlet/importable-fonts/Small Caps.js'),
  'Small Isometric1': () => import('figlet/importable-fonts/Small Isometric1.js'),
  'Small Keyboard': () => import('figlet/importable-fonts/Small Keyboard.js'),
  'Small Poison': () => import('figlet/importable-fonts/Small Poison.js'),
  'Small Script': () => import('figlet/importable-fonts/Small Script.js'),
  'Small Shadow': () => import('figlet/importable-fonts/Small Shadow.js'),
  'Small Slant': () => import('figlet/importable-fonts/Small Slant.js'),
  'Small Tengwar': () => import('figlet/importable-fonts/Small Tengwar.js'),
  'Small': () => import('figlet/importable-fonts/Small.js'),
  'Soft': () => import('figlet/importable-fonts/Soft.js'),
  'Speed': () => import('figlet/importable-fonts/Speed.js'),
  'Spliff': () => import('figlet/importable-fonts/Spliff.js'),
  'Stacey': () => import('figlet/importable-fonts/Stacey.js'),
  'Stampate': () => import('figlet/importable-fonts/Stampate.js'),
  'Stampatello': () => import('figlet/importable-fonts/Stampatello.js'),
  'Standard': () => import('figlet/importable-fonts/Standard.js'),
  'Star Strips': () => import('figlet/importable-fonts/Star Strips.js'),
  'Star Wars': () => import('figlet/importable-fonts/Star Wars.js'),
  'Stellar': () => import('figlet/importable-fonts/Stellar.js'),
  'Stforek': () => import('figlet/importable-fonts/Stforek.js'),
  'Stick Letters': () => import('figlet/importable-fonts/Stick Letters.js'),
  'Stop': () => import('figlet/importable-fonts/Stop.js'),
  'Straight': () => import('figlet/importable-fonts/Straight.js'),
  'Stronger Than All': () => import('figlet/importable-fonts/Stronger Than All.js'),
  'Sub-Zero': () => import('figlet/importable-fonts/Sub-Zero.js'),
  'Swamp Land': () => import('figlet/importable-fonts/Swamp Land.js'),
  'Swan': () => import('figlet/importable-fonts/Swan.js'),
  'Sweet': () => import('figlet/importable-fonts/Sweet.js'),
  'Tanja': () => import('figlet/importable-fonts/Tanja.js'),
  'Tengwar': () => import('figlet/importable-fonts/Tengwar.js'),
  'Term': () => import('figlet/importable-fonts/Term.js'),
  'Test1': () => import('figlet/importable-fonts/Test1.js'),
  'The Edge': () => import('figlet/importable-fonts/The Edge.js'),
  'Thick': () => import('figlet/importable-fonts/Thick.js'),
  'Thin': () => import('figlet/importable-fonts/Thin.js'),
  'THIS': () => import('figlet/importable-fonts/THIS.js'),
  'Thorned': () => import('figlet/importable-fonts/Thorned.js'),
  'Three Point': () => import('figlet/importable-fonts/Three Point.js'),
  'Ticks Slant': () => import('figlet/importable-fonts/Ticks Slant.js'),
  'Ticks': () => import('figlet/importable-fonts/Ticks.js'),
  'Tiles': () => import('figlet/importable-fonts/Tiles.js'),
  'Tinker-Toy': () => import('figlet/importable-fonts/Tinker-Toy.js'),
  'Tombstone': () => import('figlet/importable-fonts/Tombstone.js'),
  'Train': () => import('figlet/importable-fonts/Train.js'),
  'Trek': () => import('figlet/importable-fonts/Trek.js'),
  'Tsalagi': () => import('figlet/importable-fonts/Tsalagi.js'),
  'Tubular': () => import('figlet/importable-fonts/Tubular.js'),
  'Twisted': () => import('figlet/importable-fonts/Twisted.js'),
  'Two Point': () => import('figlet/importable-fonts/Two Point.js'),
  'Univers': () => import('figlet/importable-fonts/Univers.js'),
  'USA Flag': () => import('figlet/importable-fonts/USA Flag.js'),
  'Varsity': () => import('figlet/importable-fonts/Varsity.js'),
  'Wavy': () => import('figlet/importable-fonts/Wavy.js'),
  'Weird': () => import('figlet/importable-fonts/Weird.js'),
  'Wet Letter': () => import('figlet/importable-fonts/Wet Letter.js'),
  'Whimsy': () => import('figlet/importable-fonts/Whimsy.js'),
  'Wow': () => import('figlet/importable-fonts/Wow.js')
}

// Track loaded fonts
const loadedFonts = new Set<string>()

// Function to load a font
export const loadFont = async (fontName: string): Promise<boolean> => {
  if (loadedFonts.has(fontName)) {
    return true
  }

  try {
    console.log(`Loading font: ${fontName}`)
    
    const fontImporter = fontImports[fontName]
    if (!fontImporter) {
      console.warn(`Font "${fontName}" not available in current selection`)
      return false
    }
    
    const fontModule = await fontImporter()
    figlet.parseFont(fontName, fontModule.default)
    loadedFonts.add(fontName)
    console.log(`Successfully loaded font: ${fontName}`)
    return true
  } catch (error) {
    console.error(`Failed to load font ${fontName}:`, error)
    return false
  }
}

// Get list of available fonts
export const getAvailableFonts = (): string[] => {
  return Object.keys(fontImports).sort()
}

// Check if font is loaded
export const isFontLoaded = (fontName: string): boolean => {
  return loadedFonts.has(fontName)
}

// Get loaded fonts set (for reactive UI)
export const getLoadedFonts = (): Set<string> => {
  return loadedFonts
}